/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { CCM, CCMInterface } from "../CCM";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint64",
        name: "_toChainId",
        type: "uint64",
      },
      {
        internalType: "bytes",
        name: "_toContract",
        type: "bytes",
      },
      {
        internalType: "bytes",
        name: "_method",
        type: "bytes",
      },
      {
        internalType: "bytes",
        name: "_txData",
        type: "bytes",
      },
    ],
    name: "crossChain",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class CCM__factory {
  static readonly abi = _abi;
  static createInterface(): CCMInterface {
    return new utils.Interface(_abi) as CCMInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): CCM {
    return new Contract(address, _abi, signerOrProvider) as CCM;
  }
}
