/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { CCMProxy, CCMProxyInterface } from "../CCMProxy";

const _abi = [
  {
    inputs: [],
    name: "getEthCrossChainManager",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class CCMProxy__factory {
  static readonly abi = _abi;
  static createInterface(): CCMProxyInterface {
    return new utils.Interface(_abi) as CCMProxyInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): CCMProxy {
    return new Contract(address, _abi, signerOrProvider) as CCMProxy;
  }
}
