/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { ILockProxy, ILockProxyInterface } from "../ILockProxy";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "_argsBs",
        type: "bytes",
      },
      {
        internalType: "bytes",
        name: "_fromContractAddr",
        type: "bytes",
      },
      {
        internalType: "uint64",
        name: "_fromChainId",
        type: "uint64",
      },
    ],
    name: "addExtension",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "_argsBs",
        type: "bytes",
      },
      {
        internalType: "bytes",
        name: "_fromContractAddr",
        type: "bytes",
      },
      {
        internalType: "uint64",
        name: "_fromChainId",
        type: "uint64",
      },
    ],
    name: "registerAsset",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "_argsBs",
        type: "bytes",
      },
      {
        internalType: "bytes",
        name: "_fromContractAddr",
        type: "bytes",
      },
      {
        internalType: "uint64",
        name: "_fromChainId",
        type: "uint64",
      },
    ],
    name: "removeExtension",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "_argsBs",
        type: "bytes",
      },
      {
        internalType: "bytes",
        name: "_fromContractAddr",
        type: "bytes",
      },
      {
        internalType: "uint64",
        name: "_fromChainId",
        type: "uint64",
      },
    ],
    name: "unlock",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ILockProxy__factory {
  static readonly abi = _abi;
  static createInterface(): ILockProxyInterface {
    return new utils.Interface(_abi) as ILockProxyInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ILockProxy {
    return new Contract(address, _abi, signerOrProvider) as ILockProxy;
  }
}
